version = 0.1
[default.deploy.parameters]
stack_name = "LambdaLogProxyBenchmark"
resolve_s3 = true
s3_prefix = "LambdaLogProxyBenchmark"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
