AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  SuppressedLambdaLogProxyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
      CompatibleArchitectures:
        - x86_64
  SuppressedLambdaLogProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      InlineCode: |
        exports.handler = async function(event) {
          process.stdout.write(`hello\n`);
          return {
            statusCode: 200,
            body: "hello"
          }
        };
      MemorySize: 1024
      Timeout: 30
      Layers:
        - !Ref SuppressedLambdaLogProxyLayer
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/entry.sh
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  API:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
